# Generated by Django 2.0.3 on 2018-03-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.TextField(max_length=80)),
                ('adminUid', models.TextField(max_length=14)),
                ('adminPass', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('offenceId', models.AutoField(primary_key=True, serialize=False)),
                ('offenceName', models.TextField(max_length=1000)),
                ('offencePenalty', models.IntegerField(null=True)),
                ('offenceSentence', models.TextField(max_length=1000, null=True)),
                ('offenceSection', models.TextField(max_length=1000)),
            ],
        ),
    ]
