# Generated by Django 2.0.3 on 2018-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.IntegerField(primary_key=True, serialize=False)),
                ('adminName', models.TextField(max_length=80)),
                ('adminUid', models.TextField(max_length=14)),
                ('adminPass', models.TextField(max_length=15)),
            ],
        ),
    ]
