# Generated by Django 2.0.3 on 2018-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20180326_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('offenceId', models.AutoField(primary_key=True, serialize=False)),
                ('offenceName', models.TextField(max_length=1000)),
                ('offencePenalty', models.IntegerField(null=True)),
                ('offenceSentence', models.TextField(max_length=1000, null=True)),
                ('offenceSection', models.TextField(max_length=1000)),
            ],
        ),
    ]
