# Generated by Django 2.0.3 on 2018-03-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='makerModel',
        ),
    ]
